[project]
name = "confyui-aei"
version = "0.1"
description = "ConfUI Advanced Easy Installer"
readme = "README.md"
authors = [{name = "Michal Sestrienka"}]
license = "Apache-2.0"
requires-python = ">=3.10"
classifiers = []
dependencies = [
    "click",
    "aiohttp>=3.9.0",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/mse11/confyui-aei"
Changelog = "https://github.com/mse11/confyui-aei/releases"
Issues = "https://github.com/mse11/confyui-aei/issues"
CI = "https://github.com/mse11/confyui-aei/actions"

[project.scripts]
confyui-aei = "confyui_aei.cli:cli"

[project.optional-dependencies]
test = ["pytest"]
